version: '3.2'
services:

    docs:
      build:
        context: .
        dockerfile: Dockerfile.dev
      ports:
        - "9999:8000"
      volumes:
        - ../:/docs
        - ~/.ssh/idrsa:/root/.ssh/idrsa
        - ~/.git:/root/.git
